Develop sprint 6
ClevertecFrontendLab/Arterixs pull request #4
Opened 2023-03-19 17:03 UTC by Arterixs

2023-03-19 17:06 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 1.
Количество непройденных тестов: 1.

2023-03-19 17:10 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 1.
Количество непройденных тестов: 1.

2023-03-19 17:31 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 76%.
Общее количество тестов: 25.
Количество непройденных тестов: 6.

2023-03-19 20:09 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 88%.
Общее количество тестов: 25.
Количество непройденных тестов: 3.
***
**1-all-buttons.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/1-all-buttons.png)
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/10-selected-day.png)
***
**11-booking-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/11-booking-error.png)
***
**12-booking-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/12-booking-success.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/13-booking-edit-modal-view.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/9-today-is-sunday.png)
***
**booking and book rate -- booking edit modal -- check booking edit modal calendar days (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20booking%20edit%20modal%20calendar%20days%20(failed).png)
***
**booking and book rate -- booking edit modal -- check edit booking request error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20error%20(failed).png)
***
**booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679256564/edit-mobile-view.png)

2023-03-20 01:17 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 84%.
Общее количество тестов: 25.
Количество непройденных тестов: 4.
***
**1-all-buttons.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/1-all-buttons.png)
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/10-selected-day.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/13-booking-edit-modal-view.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/9-today-is-sunday.png)
***
**booking and book rate -- booking edit modal -- check booking edit modal calendar days (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20booking%20edit%20modal%20calendar%20days%20(failed).png)
***
**booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)
***
**booking and book rate -- booking modal -- check booking request error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/booking%20and%20book%20rate%20--%20booking%20modal%20--%20check%20booking%20request%20error%20(failed).png)
***
**booking and book rate -- booking modal -- check booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/booking%20and%20book%20rate%20--%20booking%20modal%20--%20check%20booking%20request%20success%20(failed).png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679275022/edit-mobile-view.png)

2023-03-20 02:26 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 25.
Количество непройденных тестов: 0.
***
**1-all-buttons.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/1-all-buttons.png)
***
**10-selected-day.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/10-selected-day.png)
***
**11-booking-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/11-booking-error.png)
***
**12-booking-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/12-booking-success.png)
***
**13-booking-edit-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/13-booking-edit-modal-view.png)
***
**14-modal-edited-date.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/14-modal-edited-date.png)
***
**15-rate-modal.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/15-rate-modal.png)
***
**16-rate-modal-mobile.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/16-rate-modal-mobile.png)
***
**17-rate-filled.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/17-rate-filled.png)
***
**18-comments-updated-sort.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/18-comments-updated-sort.png)
***
**2-booking-modal-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/2-booking-modal-view.png)
***
**3-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/3-mobile-view.png)
***
**4-january.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/4-january.png)
***
**5-december-2022.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/5-december-2022.png)
***
**6-february.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/6-february.png)
***
**7-today-is-friday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/7-today-is-friday.png)
***
**8-today-is-saturday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/8-today-is-saturday.png)
***
**9-today-is-sunday.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/9-today-is-sunday.png)
***
**edit-mobile-view.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Arterixs/1679279169/edit-mobile-view.png)

2023-03-20 06:35 UTC, Ivan6813 requested changes

2023-03-20 06:35 UTC, Ivan6813 commented on src/components/auth/check-mark/check.tsx
> +    <use href='#check-mark' />
бургер меню не должно быть видно

![msedge_NG2JyPQ4M4](https://user-images.githubusercontent.com/79784960/226262710-97c398c0-1027-4854-b95d-795dd1077b65.png)

2023-03-20 06:35 UTC, Ivan6813 commented on src/components/book-page/stars-empty.tsx
> +    <svg className='star-empty' data-test-id='star'>
используй map

2023-03-20 06:35 UTC, Ivan6813 commented on src/components/book-page/stars-full.tsx
> +      <use href='#star-full' data-test-id='star-active' />
map

2023-03-20 06:35 UTC, Ivan6813 commented on src/components/header.tsx
> +        {isOpen ? <WindowMessage /> : null}
`{ isOpen && <WindowMessage /> }`

2023-03-20 08:11 UTC, Arterixs commented on src/components/book-page/stars-empty.tsx
> +    <svg className='star-empty' data-test-id='star'>
исправил

2023-03-20 08:11 UTC, Arterixs commented on src/components/book-page/stars-full.tsx
> +      <use href='#star-full' data-test-id='star-active' />
исправил

2023-03-20 08:11 UTC, Arterixs commented on src/components/header.tsx
> +        {isOpen ? <WindowMessage /> : null}
исправил

2023-03-20 08:11 UTC, Arterixs commented on src/components/auth/check-mark/check.tsx
> +    <use href='#check-mark' />
исправил

2023-03-20 08:11 UTC, Arterixs commented on src/components/book-page/stars-empty.tsx
> +    <svg className='star-empty' data-test-id='star'>
исправил

2023-03-20 08:11 UTC, Arterixs commented on src/components/book-page/stars-full.tsx
> +      <use href='#star-full' data-test-id='star-active' />
исправил

2023-03-20 08:24 UTC, Ivan6813 approved these changes

2023-03-20 08:25 UTC, merged